language: java
jdk: oraclejdk8

#safelist -- ensures only commits to master branch triggers the builds
branches:
  only:
  - master
  
before_install:
  - pip install --user codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
script:
  - "mvn cobertura:cobertura"
 
