language: java
jdk: oraclejdk8

#safelist -- ensures only commits to master branch triggers the builds
branches:
  only:
  - master 
  
script:
  - "mvn cobertura:cobertura"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  

 
